### ISSUE TITLE
Error in version 2.0.5

### ISSUE THREAD

**Issue by Okami-x-Senpai** [marcoscgdev/DialogSheet#11]
When I **try to use the dialog** it shows me the following error in the **Logcat**:

```
2019-04-22 13:09:15.454 7136-7136/com.raven.okami E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.raven.okami, PID: 7136
    android.view.InflateException: Binary XML file line #6: Binary XML file line #32: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class TextView
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:548)
        at android.widget.TextView.readTextAppearance(TextView.java:3552)
        at android.widget.TextView.<init>(TextView.java:924)
        at android.widget.TextView.<init>(TextView.java:869)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:91)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:999)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.google.android.material.bottomsheet.BottomSheetDialog.wrapInBottomSheet(BottomSheetDialog.java:135)
        at com.google.android.material.bottomsheet.BottomSheetDialog.setContentView(BottomSheetDialog.java:70)
        at com.marcoscg.dialogsheet.DialogSheet.init(DialogSheet.java:383)
        at com.marcoscg.dialogsheet.DialogSheet.<init>(DialogSheet.java:61)
        at com.raven.okami.LogIn$3.onFailure(LogIn.java:271)
        at com.google.android.gms.tasks.zzl.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2019-04-22 13:09:15.512 739-739/? E/lowmemorykiller: Error writing /proc/7136/oom_score_adj; errno=22
2019-04-22 13:09:15.564 2284-2376/? E/InputDispatcher: channel '52139b6 com.raven.okami/com.raven.okami.LogIn (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-04-22 13:09:15.603 2284-3371/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.miui.home/com.miui.home.launcher.Launcher/40930015
2019-04-22 13:09:18.657 2284-2469/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
```

Also, the color of the _"OK"_ button does not have the **background color of the Accent color**.

**Comment by marcoscgdev** [comment]
Please can you provide the dialog code? It seems to be a problem with the content view.

**Comment by Okami-x-Senpai** [comment]
This is my code:
```
                new DialogSheet(LogIn.this)
                        .setTitle(LogIn.this.getString(R.string.raven_network_title_dialogs))
                        .setIconResource(R.drawable.ic_info_notice)
                        .setBackgroundColorRes(R.color.colorObjects)
                        .setRoundedCorners(false)
                        .setColoredNavigationBar(true)
                        .setCancelable(true)
                        .setMessage(LogIn.this.getString(R.string.main_login_info_message_error_processing_account)
                                + "\n\n" + e.getLocalizedMessage())
                        .setPositiveButton(LogIn.this.getString(R.string.raven_default_title_button_retry), new DialogSheet.OnPositiveClickListener() {
                            @Override
                            public void onClick(View v) {
                                mRavenLoader.setLabel(LogIn.this.getString(R.string.raven_default_title_loader));
                                mRavenLoader.setDetailsLabel(LogIn.this.getString(R.string.raven_default_desc_loader));
                                mRavenLoader.setStyle(KProgressHUD.Style.SPIN_INDETERMINATE);
                                mRavenLoader.setCancellable(false);
                                mRavenLoader.setAnimationSpeed(1);
                                mRavenLoader.setDimAmount(0.5f);
                                mRavenLoader.show();
                                LogIn.this.logInRavenNetwork(mEmailData, mPasswordData);
                            }
                        }).setNegativeButton(LogIn.this.getString(R.string.raven_default_title_button_cancel), new DialogSheet.OnNegativeClickListener() {
                    @Override
                    public void onClick(View v) {
                        mAuth.signOut();
                        Snacky.builder()
                                .setBackgroundColor(Color.parseColor("#111111"))
                                .setActivity(LogIn.this)
                                .setText(LogIn.this.getString(R.string.raven_info_default_message_error_null))
                                .setDuration(Snacky.LENGTH_LONG)
                                .success()
                                .show();
                    }
                }).show();
```

**Comment by marcoscgdev** [comment]
The problem is that you are not adding this attribute to your app theme:

`<item name="dialogSheetAccent">@color/colorAccent</item>`

The attribute is required by this library.

**Comment by Okami-x-Senpai** [comment]
But then that's why I can not show the Dialog? Why with this version does not let me start it like I did before.

**Comment by marcoscgdev** [comment]
Yes, that's why you can not show the dialog. Everything works like before, but with the new library release, It is mandatory to add that attribute to the app theme.

**Comment by Okami-x-Senpai** [comment]
Excellent, it works perfectly for me now, thank you very much.

**Comment by marcoscgdev** [comment]
You are welcome :smile:
