### ISSUE TITLE
Erro - Opening Dialog.

### ISSUE THREAD

**Issue by lucazin** [marcoscgdev/DialogSheet#27]
In my activity i have a webp with background.. when i open this dialog give this exception.
Without works fine.

Can u help me marcos?

Fatal Exception: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/imagem_oneplace_fundo_bg.webp from drawable resource ID #0x7f0803ae: .xml extension required
       at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1249)
       at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:1067)
       at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1146)
       at android.content.res.Resources.loadColorStateList(Resources.java:1077)
       at android.content.res.TypedArray.getColor(TypedArray.java:519)
       at com.marcoscg.dialogsheet.Utils.getAttrColor(Utils.java:48)
       at com.marcoscg.dialogsheet.DialogSheet.show(DialogSheet.java:407)
       at aplicativo.oneplace.Suporte.BaseConfig.Activity.BaseActivityCredentials.onBackPressed(BaseActivityCredentials.java:1477)

**Comment by lucazin** [comment]
this line here

  fun show() {
        if (backgroundColor == 0) backgroundColor = getAttrColor(context, android.R.attr.windowBackground)


![image](https://user-images.githubusercontent.com/28266902/94033326-39cf5700-fd97-11ea-9512-491cdf8198d2.png)

 I think you are expecting just a color.. but i have a bg in my activity.

How can fix this?

**Comment by marcoscgdev** [comment]
You are right. I am expecting a background window color instead of an image. I will work on it.

**Comment by lucazin** [comment]
Thanks!

**Comment by marcoscgdev** [comment]
Fixed in [version 2.1.2](https://github.com/marcoscgdev/DialogSheet/releases/tag/2.1.2).
